//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceFly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int ID { get; set; }
        public string PreFix { get; set; }
        public string Route_Id { get; set; }
        public string Plane_Id { get; set; }
        public string Day { get; set; }
        public Nullable<System.TimeSpan> Arrival_Time { get; set; }
        public Nullable<System.TimeSpan> Departure_Time { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<double> Price_B { get; set; }
        public Nullable<double> Price_E { get; set; }
    
        public virtual Plane Plane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
