//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceFly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string PreFix { get; set; }
        public string Ticket_Id { get; set; }
        public string Transaction_Id { get; set; }
        public string passenger_name { get; set; }
        public string seatNo { get; set; }
        public string schedule_ID { get; set; }
        public string Ticket_status { get; set; }
        public string Passenger_type { get; set; }
        public string email { get; set; }
        public string document_type { get; set; }
        public string document_no { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual user_details user_details { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
